const MUSEUMS = [
  "National Museum of Bangladesh",
  "Bangladesh National Museum",
  "Folk Art Museum",
  "Varendra Research Museum",
  "Liberation War Museum",
  "Ahsan Manzil Museum",
  "Bangabandhu Memorial Museum",
  "Osmani Museum",
  "Ethnological Museum of Chittagong",
  "Mymensingh Museum",
  "Zainul Abedin Sangrahashala",
  "Bangladesh Air Force Museum",
  "Bangladesh Military Museum",
  "Bangladesh Museum of Independence",
  "Mainamati Museum",
  "Paharpur Museum",
  "Mahasthangarh Museum",
  "Rangpur Museum",
  "Comilla Cantonment Museum",
  "Sylhet Divisional Museum",
  "Khulna Divisional Museum",
  "Rajshahi University Museum",
  "Dhaka University Museum",
  "Chittagong University Museum",
  "Zia Memorial Museum",
  "Bijoy Keton Museum",
  "Tajhat Palace Museum",
  "Natore Rajbari Museum",
  "Bagha Mosque Museum",
  "Shilaidaha Kuthibari Museum",
  "Kantajew Temple Museum",
  "Sitakot Vihara Museum",
  "Wari-Bateshwar Museum",
  "Panam City Heritage Museum",
  "Lalbagh Fort Museum",
  "Shaheed Minar Museum",
  "Sundarban Ecological & Cultural Museum",
  "Barisal Divisional Museum",
  "Jessore Museum",
  "Bogura Museum",
  "Feni Museum",
  "Cumilla Museum",
  "Chandpur Museum",
  "Noakhali Museum",
  "Moulvibazar Museum",
  "Habiganj Museum",
  "Dinajpur Museum",
  "Bagerhat Museum",
  "Patuakhali Museum",
  "Cox's Bazar Museum",
  "Khagrachari Museum",
  "Rangamati Museum",
  "Bandarban Museum",
  "Narail Museum",
  "Gazipur Museum",
  "Narsingdi Museum",
  "Tangail Museum",
  "Faridpur Museum",
  "Manikganj Museum",
  "Satkhira Museum",
  "Magura Museum",
  "Jhenidah Museum",
  "Brahmanbaria Museum",
  "Netrokona Museum",
  "Sherpur Museum",
  "Gaibandha Museum",
  "Sirajganj Museum",
  "Pabna Museum",
  "Naogaon Museum",
  "Joypurhat Museum",
  "Kushtia Museum",
  "Chuadanga Museum",
  "Madaripur Museum",
  "Gopalganj Museum",
  "Lakshmipur Museum",
  "Bhola Museum",
  "Natore Museum",
  "Jamalpur Museum",
  "Nilphamari Museum",
  "Thakurgaon Museum",
  "Lalmonirhat Museum",
  "Kurigram Museum",
  "Munshiganj Museum",
  "Rajbari Museum",
  "Bhola District Museum",
  "Chapai Nawabganj Museum",
  "Panchagarh Museum",
  "Meherpur Museum",
  "Shariatpur Museum",
  "Mymensingh District Museum",
  "Barguna Museum",
  "Pirojpur Museum",
  "Hatiya Heritage Museum",
  "Sonargaon Folk Art Museum",
  "Sundarbans Museum",
  "Dhaka City Museum",
  "Bangladesh Heritage Museum",
  "Chattogram Museum",
  "Sylhet Museum of History",
  "Rajshahi Museum",
  "Khulna Museum",
  "Barishal Museum",
  "Rangpur Art and Culture Museum",
  "Narayanganj Heritage Museum",
  "Muktijuddha Museum",
  "Bangladesh Agricultural Museum",
  "Bhandari Museum",
  "Bhawal National Museum",
  "Tanguar Haor Interpretation Centre",
  "Suktagandha Museum",
  "Bhashani Museum",
  "Deepchori Museum",
  "Madhabpur Lake Museum",
  "Bagerhat Heritage Museum",
  "Kumrakathi Museum",
  "Shibganj Museum",
  "Chaugachha Museum",
  "Bogra District Museum",
  "Chandpur Cultural Museum",
  "Ramu Museum",
  "Coxs Bazar Discovery Museum"
];

const MUSEUM_SET = new Set(MUSEUMS.map((name) => name.trim()));

function normalizeMuseumName(name) {
  return (name || "").trim();
}

function isValidMuseumName(name) {
  const cleaned = normalizeMuseumName(name);
  return Boolean(cleaned) && MUSEUM_SET.has(cleaned);
}

module.exports = { MUSEUMS, MUSEUM_SET, normalizeMuseumName, isValidMuseumName };
